name: Publish packages to OSSRH

on:
  push:
    paths:
      - lang/**
    branches:
      - master
      - version-[0-9].[0-9]+.x
    tags:
      - v[0-9].[0-9]+.[0-9]+
  pull_request:
    paths:
      - lang/**

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-cache-${{ hashFiles('project/build.properties') }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-cache
      - name: Prepare version
        id: sbt-version
        run: |
          sbt_version=$(cut -d\" -f2 version.sbt)
          git_ref=${GITHUB_REF##*/}
          pr_number=${{ github.event.number }}
          if [[ $git_ref =~ v[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
            if [[ v$sbt_version != $git_ref ]] ; then
              echo SBT version $sbt_version does not match tag $git_ref
              exit 1
            fi
          else
            if [[ $pr_number != "" ]] ; then
              sbt_version=$sbt_version-$pr_number-SNAPSHOT
            else
              sbt_version=$sbt_version-SNAPSHOT
            fi
            echo "version := \"$sbt_version\"" >> version.sbt
            echo Setting version to $sbt_version
          fi
      - name: Publish package
        id: sbt-publish
        run: |
          sbt ";lang/publishSigned;lang/sonatypeRelease"
